title: Melissa Kendall
description: Website for Melissa Kendall.
baseurl: "" 
url: "http://melissakendall.ca" 
github_username: melissakendall
instagram_username: calicoella
twitter_username: Occasita
google_analytics: UA-136093723-1
author_name: "Melissa Kendall"

markdown: kramdown
