title: Melissa Kendall
description: Website for Melissa Kendall.
baseurl: "" 
url: "http://melissakendall.ca" 
github_username: melissakendall
instagram_username: calicoella
twitter_username: Occasita
linkedin_username: melissa-kendall-72b35195
google_analytics: UA-136093723-1

markdown: kramdown
